apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc
spec:
  replicas: 5
  selector:
    matchLabels:
      app: poc
  template:
    metadata:
      labels:
        app: poc
    spec:
      containers:
        - name: poc
          image: 020436079950.dkr.ecr.us-east-1.amazonaws.com/poc-repo:latest
          ports:
            - containerPort: 8080
