#spring.datasource.url=jdbc:mysql://pocdb.cluster-cipwprgh221p.us-east-1.rds.amazonaws.com:3306/javadevjournal

management:
  health:
    probes:
      enabled: true

spring:
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  profiles:
    active: dev
