spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1-instance-1.cipwprgh221p.us-east-1.rds.amazonaws.com:3306/pocdb?useSSL=false&serverTimezone=UTC
    username: admin
    password: Feud640yarn413
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:
    stream:
      function:
        definition: ledgerConsumer; resultProducer;
      kafka:
        binder:
          brokers: b-1.poc-msk-cluster1.9alykk.c16.kafka.us-east-b-2.poc-msk-cluster1.9alykk.c16.kafka.us-east-1.amazonaws.com:9092,b-1.poc-msk-cluster1.9alykk.c16.kafka.us-east-1.amazonaws.com:9092
          #configuration:
            #key:
              #deserializer: org.apache.kafka.common.serialization.StringDeserializer
              #serializer: org.apache.kafka.common.serialization.StringSerializer
            #value:
              #deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
              #serializer: org.apache.kafka.common.serialization.ByteArraySerializer
        bindings:
          ledgerConsumer-in-0:
            consumer:
              enableDlq: false
              #dlqName: poc-inqueue-dlq-v1
              ack-mode: BATCH

      bindings:
        ledgerConsumer-in-0:
          destination: poc-inbound
          group: inbound
        resultProducer-out-0:
          consumer:
            destination: poc-outbound