management:
  health:
    probes:
      enabled: true

spring:
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  profiles:
    active: dev

  devtools:
    livereload:
      port: 35731
debug: true
